### ISSUE TITLE
Firewall-rules error

### ISSUE THREAD

**Issue by matthewfade** [bigmoby/homeassistant_nat_network#1]
Ciao,
al momento in cui provo ad inserire la regola $ gcloud compute firewall-rules create wireguardrule --allow udp:51820 la VM restituisce l'errore in allegato.

Dove sbaglio?
Grazie mille per un supporto

![Immagine 2020-11-11 134300](https://user-images.githubusercontent.com/65716964/98813029-d91ddb80-2423-11eb-97c8-d8a2e1f2e260.png)

**Comment by bigmoby** [comment]
Ciao, credo che non stai eseguendo il comando come superuser. Prova preliminarmente ad accedere come su invocando:

`sudo su`

**Comment by matthewfade** [comment]
Faccio sudo su e restituisce la stringa 
root@....

faccio la rules ma da sempre l'errore
