### ISSUE TITLE
Problems with GCP

### ISSUE THREAD

**Issue by domoZAM** [bigmoby/homeassistant_nat_network#10]
Hi, I followed  your suggestion in the previous issue:
[https://github.com/bigmoby/homeassistant_nat_network/issues/9](url)

but I found some problems to follow till the end:

pinco@cloudshell:~ (axial-matter-xyz)$ sudo apt install linux-image-4.19.0-13-rt-amd64/stable
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Selected version '4.19.160-2' (Debian:10.8/stable [amd64]) for 'linux-image-4.19.0-13-rt-amd64'
Suggested packages:
  linux-doc-4.19 debian-kernel-handbook grub-pc | grub-efi-amd64 | extlinux
The following NEW packages will be installed:
  firmware-linux-free linux-image-4.19.0-13-rt-amd64
0 upgraded, 2 newly installed, 0 to remove and 7 not upgraded.
Need to get 48.4 MB of archives.
After this operation, 271 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://deb.debian.org/debian buster/main amd64 firmware-linux-free all 3.4 [19.2 kB]
Get:2 http://deb.debian.org/debian buster/main amd64 linux-image-4.19.0-13-rt-amd64 amd64 4.19.160-2 [48.4 MB]
Fetched 48.4 MB in 1s (57.6 MB/s)                         
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package firmware-linux-free.
(Reading database ... 115085 files and directories currently installed.)
Preparing to unpack .../firmware-linux-free_3.4_all.deb ...
Unpacking firmware-linux-free (3.4) ...
Selecting previously unselected package linux-image-4.19.0-13-rt-amd64.
Preparing to unpack .../linux-image-4.19.0-13-rt-amd64_4.19.160-2_amd64.deb ...
mkdir: cannot create directory ‘/lib/modules/4.19.0-13-rt-amd64’: Read-only file system
dpkg: error processing archive /var/cache/apt/archives/linux-image-4.19.0-13-rt-amd64_4.19.160-2_amd64.deb (--unpack):
 new linux-image-4.19.0-13-rt-amd64 package pre-installation script subprocess returned error exit status 1
W: Last kernel image has been removed, so removing the default symlinks
Errors were encountered while processing:
 /var/cache/apt/archives/linux-image-4.19.0-13-rt-amd64_4.19.160-2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
pinco@cloudshell:~ (axial-matter-xyz)$

Any suggestion more?

Thank you
ZAM

**Comment by bigmoby** [comment]
Hi @domoZAM ,
I as far as I understand `pinco@cloudshell:~ (axial-matter-xyz)$ sudo apt install linux-image-4.19.0-13-rt-amd64/stable` you have invoked that not logged as root, so, I suggested to invoke the above command only after a root login...in other words you have to invoke `sudo su` before!

**Comment by domoZAM** [comment]
I tried but it's the same:

root@cs-573493490656-default-boost-k6fwg:/home/pinco# apt install linux-image-4.19.0-13-rt-amd64/stable
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Selected version '4.19.160-2' (Debian:10.8/stable [amd64]) for 'linux-image-4.19.0-13-rt-amd64'
Suggested packages:
  linux-doc-4.19 debian-kernel-handbook grub-pc | grub-efi-amd64 | extlinux
The following NEW packages will be installed:
  linux-image-4.19.0-13-rt-amd64
0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.
1 not fully installed or removed.
Need to get 48.4 MB of archives.
After this operation, 271 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 linux-image-4.19.0-13-rt-amd64 amd64 4.19.160-2 [48.4 MB]
Fetched 48.4 MB in 1s (58.5 MB/s)                         
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 115119 files and directories currently installed.)
Preparing to unpack .../linux-image-4.19.0-13-rt-amd64_4.19.160-2_amd64.deb ...
mkdir: cannot create directory ‘/lib/modules/4.19.0-13-rt-amd64’: Read-only file system
dpkg: error processing archive /var/cache/apt/archives/linux-image-4.19.0-13-rt-amd64_4.19.160-2_amd64.deb (--unpack):
 new linux-image-4.19.0-13-rt-amd64 package pre-installation script subprocess returned error exit status 1
W: Last kernel image has been removed, so removing the default symlinks
Errors were encountered while processing:
 /var/cache/apt/archives/linux-image-4.19.0-13-rt-amd64_4.19.160-2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@cs-573493490656-default-boost-k6fwg:/home/pinco#

But my doubt is this: why i meet these problems that weren't in your guide? It depend from some choose i 've done, or other ?
If it's too complicate to support me or you re-wrote another guide for me, never mind, ..i wouldn't be too challenging for your plans.
Thank you for your patience..

**Comment by bigmoby** [comment]
Hi @domoZAM 
I don't know sincerely what could be the issue related to `mkdir: cannot create directory ‘/lib/modules/4.19.0-13-rt-amd64’: Read-only file system`. Could you please give me the result for a `ls -lah /lib/modules` in order to understand the rights and the own for this directory?

**Comment by domoZAM** [comment]
Hi bigmoby, this the output at your request:
root@cs-573493490656-default-boost-tbwxj:/home/pinco# ls -lah /lib/modules/
total 12K
drwxr-xr-x 3 root root 4.0K Feb  5 04:20 .
drwxr-xr-x 1 root root 4.0K Feb 23 12:39 ..
drwxr-xr-x 4 root root 4.0K Feb  5 04:22 5.4.89+
root@cs-573493490656-default-boost-tbwxj:/home/pinco#

**Comment by bigmoby** [comment]
😅I don't know...really, from "remote" is hard!
You could try to install a different kernel version like `sudo apt install linux-image-4.9.0-14-amd64`
Or try to update you OS like `sudo apt update && sudo apt dist-upgrade`

**Comment by domoZAM** [comment]
OK, i will try, thank You! 
But you think that probably changing Zone (for example from zurich to frankfurt), with different HW could be change the behaviour, because all what you explain in your guide has worked.. why in m case do not?

Anyway, thank anymore.

**Comment by bigmoby** [comment]
> OK, i will try, thank You!
> But you think that probably changing Zone (for example from zurich to frankfurt), with different HW could be change the behaviour, because all what you explain in your guide has worked.. why in m case do not?
> 
> Anyway, thank anymore.

Mmm...it sounds me weird, I don't think could be that!
I'll try to change kernel image (?!?!?!) o distro from buster to bullseye in order to "shuffle the cards" and probably throws a more explicit error message.
I'm sorry for that
