### ISSUE TITLE
Prova gratuita google cloud platform

### ISSUE THREAD

**Issue by dnamat88** [bigmoby/homeassistant_nat_network#12]
Ciao,
dopo la prova gratuita del google cloud platform il plugin ha finito di funzionare ovvero non ha più reso possibile il collegamento fuori wifi di casa.
ho provato solo ora (dopo diversi mesi) a rientrare in google cloud platform ed il mio progetto non esiste più.

1) esiste una soluzione per ripristinare il progetto?
2) avevo ancora circa 230 euro rimanenti... se ne inizio uno nuovo continuano a scalare questo credito?

**Comment by bigmoby** [comment]
Ciao, no non è possibile che la virtual machine creata in Google Cloud sia stata rimossa automaticamente. Inoltre l'add-on non è assolutamente associato con Google Cloud ovvero se ha un server wireguard a cui collegarsi lui va avanti a collegarsi, non è un problema relativo all' addon. Come consiglio personale posso dirti di verificare che non hai rimosso (evidentemente in modo involontario) tutta l'installazione della vm. Inoltre il periodo di prova dovrebbe durare un anno non pochi mesi come in questo caso.

**Comment by dnamat88** [comment]
Ho sentito l'assistenza di google. Dopo il periodo di prova mi hanno
cancellato il progetto... 🤦‍♂️ Quindi ho perso tutto ed ora dovrei pagare
mensilmente quello che consumo. Peccato.. Devo trovare un altro modo..
Consigli?

Il Sab 15 Mag 2021, 07:41 BigMoby ***@***.***> ha scritto:

**Comment by bigmoby** [comment]
Ciao, credo che quando hai creato l'infrastruttura tu abbia creato qualche risorsa "di troppo" 😅 Ti spiego, il programma di prova di Google Cloud si esaurisce o a tempo (e nel tuo caso lo escludo essendo stato creato, vado a memoria, circa 3/4 mesi fa) oppure a consumo di risorse ovvero quante più risorse allochiamo (cpu, localizzazioni più performanti, ecc...) e prima si esaurisce il credito residuo. Credo tu sia incappato nel secondo caso.
Ti consiglio di attenerti alla creazione delle risorse essenziali riportate in guida tenendoti ai valori più bassi di spesa. Temo ti tocca ricrearti tutto da capo ed eventualmente pagare quei pochissimi centesimi (all'euro difficilmente si arriva) al mese.

**Comment by dnamat88** [comment]
Mi hanno assicurato che era finito il tempo. Di credito ne avevo ancora a
bizzeffe.. Proverò di nuovo appena ho tempo :(

Il Ven 21 Mag 2021, 10:56 BigMoby ***@***.***> ha scritto:

**Comment by bigmoby** [comment]
https://cloud.google.com/free/docs/gcp-free-tier?hl=it#:~:text=Il%20Programma%20gratuito%20di%20Google%20Cloud%20comprende%3A,prodotti%20e%20servizi%20Google%20Cloud.

È purtroppo cambiato il termine del periodo di prova!
