### ISSUE TITLE
NGINX certificates issues - certbox

### ISSUE THREAD

**Issue by Lele855** [bigmoby/homeassistant_nat_network#13]
Ciao,

grazie mille per la guida, molto chiara! ho seguito sia questa guida che l'altra che hai pubblicato su vincenzo caputo (https://www.vincenzocaputo.com/langolo_dei_lettori/accedere-ad-home-assistant-da-una-rete-di-tipo-nat-volume-2-584), per l'utilizzo del protocollo https con certbox. sono arrivato alla creazione dei certificati ma riscontro l'errore indicato nella schermata : 
<img width="1071" alt="Schermata 2022-05-22 alle 11 10 45" src="https://user-images.githubusercontent.com/60370555/169688502-42e9d2d5-f1ea-4db3-9980-17ad3341a557.png">

_IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: angera9.duckdns.org
   Type:   connection
   Detail: 81......192: Fetching
   http://xxxxxxx.duckdns.org/.well-known/acme-challenge/zGsLKuTUl6PTjEyLobGc-O5AkbDDWceT3XuUIwN8QD0:
   Timeout during connect (likely firewall problem)

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided._

il file di configurazione di ngix è stato fatto seguendo le indicazioni della guida

server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name lamiacasadicampagna.duckdns.org;
        location / {
                proxy_pass http://10.6.0.2:8123; (--> qui ho messo l'indirizzo che leggo su DUCKDNS, o devo lasciare questo? ho in ogni caso provato entrambi gli indirizzi ma i certificati non vengono scaricati)
                proxy_redirect off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $server_name;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                chunked_transfer_encoding off;
                proxy_buffering off;
                proxy_cache off;

mi aiuti a capire dove sbaglio? ho ILIAD fibra come operatore, non so se influisce, ho letto di qualche implicazione a livello di porte..

ciao, grazie

Samuele

**Comment by bigmoby** [comment]
Ciao, ti ringrazio per i complimenti!
Si tratta con molta probabilità (così viene anche riportato dal log di certbot) di un problema di porte chiuse. Verifica che abbia delle policy di redirect sulle porte 80 e 433 verso il server che si occuperà di detenere il certificato. 👍
Ti riporto per completezza: https://letsencrypt.org/docs/allow-port-80/

**Comment by bigmoby** [comment]
Rivedi questo step: https://github.com/bigmoby/homeassistant_nat_network/blob/main/README_IT_part_2.md#installazione-di-certbot
ed in particolare: 
<img width="1073" alt="Screenshot 2022-05-22 at 14 22 58" src="https://user-images.githubusercontent.com/11453002/169694923-d6fc5e37-880a-4b5e-8829-a0c4c2c95bd1.png">

**Comment by Lele855** [comment]
Ciao Bigmoby, scusami per vari motivi ho dovuto riapplicare le varie configurazioni e mi sono bloccato di nuovo (non sul punto di questa issue, ma volevo continuare da qui senza aprirne un'altra). in pratica mi sono perso sugli indirizzi da mettere lato client/home assistant (ho hassio e ho installato il tuo componente aggiuntivo wireguard, cercando di applicare le ultime news citate qui https://github.com/bigmoby/hassio-repository-addon/blob/main/wireguard-client/CHANGELOG.md) 

in pratica tu nella guida usi 10.6.0.2, ma questo che cosa rappresenta? è l'indirizzo locale del raspberry dove gira HA oppure altro?
al momento gli indirizzi IP che ho presenti sono (indirizzo IP interno ed esterno della VM GCP, indirizzo IP che si legge su DUCKDNS e indirizzo IP locale del raspberry, 192.168.x.x).

mi chiarisci quale vada usato?
ciao, grazie

Samuele

**Comment by bigmoby** [comment]
Ciao @Lele855 ,
l'indirizzo 10.6.0.2, e in generale gli indirizzi che assegnerai alle macchine della VPN, li puoi scegliere liberamente tu, non sono gli indirizzi fisici delle macchine sulla tua lan. 
Segui passo-passo entrambe le parti della guida:
- https://github.com/bigmoby/homeassistant_nat_network/blob/main/README.md
- https://github.com/bigmoby/homeassistant_nat_network/blob/main/README_IT_part_2.md

e non ti sbaglierai ;-)

**Comment by Lele855** [comment]
ah ok perfetto, quindi posso usare tranquillamente il 10.6.0.2 come hai fatto tu senza alcun problema. giusto? rimarrebbe quindi di sostituire il dominio duckdns da te utilizzato nella guida con il mio xxx.duckdns.org. corretto?

grazie!
