### ISSUE TITLE
400: Bad Request

### ISSUE THREAD

**Issue by sginestrini** [bigmoby/homeassistant_nat_network#15]
Ciao Fabio,

Ho seguito entrambe le parti della guida. 
Al termine della prima parte avevo http://dominio.duckdns.org che rispondeva correttamente ma la rete sul raspy morta, i comandi di "ping qualsiasi dominio o ip" non rispondevano e su HA avevo tutti i servizi che necessitavano di rete (meteo, HACS, ecc..) down.
Ho comunque proseguito con la seconda parte della guida, ottenendo di non riuscire più a connettermi ne con http ne con https (sia da rete locale che esterna) con errore "502 Bad Gateway". Specifico che il test per il certificato SSL va a buon fine, cosi come `sudo nginx -t`

Ho quindi lanciato il comando
`$ sudo systemctl disable wg-quick@wg0-client`
per vedere se fosse un problema della vpn e disabilitandola internet ha ripreso a funzionare correttamente (ma chiaramente non duckdns).
Rilanciando poi i due comandi
```
$ sudo systemctl start wg-quick@wg0-client
$ sudo systemctl enable wg-quick@wg0-client
```
Internet ha continuato ad andare correttamente ma in compenso adesso se provo ad accedere a https://dominio.duckdns.org mi risponde con "400: Bad Request" sia da rete locale che esterna.
Ho ovviamente riavviato sia client che GC in tutti questi passaggi e controllato che i servizi fossero attivi, tutti i file sembrano correttamente configurati.

Ho fatto il Port mapping della porta 51820:
![immagine](https://github.com/bigmoby/homeassistant_nat_network/assets/11695134/2c58f8eb-fa61-4a4e-b71d-51dbc2005dd4)

Questo è il servizio wireguard su client:
![immagine](https://github.com/bigmoby/homeassistant_nat_network/assets/11695134/4a601a09-1ad1-4fc3-9eaf-11044415d90d)

Queste le regole del firewall su GC:
![immagine](https://github.com/bigmoby/homeassistant_nat_network/assets/11695134/26fba2be-8784-4aa8-838e-8601da6bf6e4)

Qualche idea?
Grazie mille

**Comment by sginestrini** [comment]
Risolto.
Sui log di HA era presente un errore che mi segnalava un tentativo di connessione dal reverse proxy
```
Logger: homeassistant.components.http.forwarded
Source: components/http/forwarded.py:114
Integration: HTTP (documentation, issues)
First occurred: 09:46:19 (2 occurrences)
Last logged: 09:46:20

A request from a reverse proxy was received from **IP**, but your HTTP integration is not set-up for reverse proxies
```

Aggiungendo sul configuration.yaml il seguente pezzo si è risolto:
```
http:
  use_x_forwarded_for: true
  trusted_proxies:
   - **IP**
```

**Comment by bigmoby** [comment]
Ottimo 😉👍
