### ISSUE TITLE
Firewall-rules error2

### ISSUE THREAD

**Issue by matthewfade** [bigmoby/homeassistant_nat_network#2]
Ciao bigmoby,
nonostante faccio "sudo su" non va comunque (vedi allegato).

Grazie per un supporto
Ciao
![Cattura](https://user-images.githubusercontent.com/65716964/98821609-11c3b200-2430-11eb-98e2-89b5b8c6784f.PNG)

**Comment by bigmoby** [comment]
Ciao, sembrerebbe che la tua utenza Google non abbia i diritti ad accedere alle risorse della tua istanza. Effettua l'autenticazione dell'account che stai usando:
`gcloud auth login`
E segui le indicazioni del processo di autorizzazione.

https://cloud.google.com/sdk/gcloud/reference/auth/login

**Comment by matthewfade** [comment]
Ok creata!
Grazie mille... spero di non stressarti più...
