### ISSUE TITLE
Error duck.sh

### ISSUE THREAD

**Issue by matthewfade** [bigmoby/homeassistant_nat_network#3]
Eccomi di nuovo qua...

faccio quanto descritto, inserisco la stringa 
echo url="https://www.duckdns.org/update?domains=lamiacasadicampagnia&token=[inserire_qui_il_token_di_duckdns]&ip=" | curl -k -o ./duck.log -K - 

sostituendo il tuo domains con il mio, inserisco il token duckdns dove da te indicato, dopo ip= devo lasciatore vuoto o cosa devo inserire???

Lascio vuoto, vado avanti con la procedura ma quando faccio 

./duck.sh

la VM restituisce l'errore in allegato.

Ho provato anche ad andare avanti con la procedura (pivpn)... ma all'inserimento della stringa 

curl -L https://install.pivpn.io | bash
![Cattura4](https://user-images.githubusercontent.com/65716964/98847854-2ebcad00-2451-11eb-99f7-c70dab61beb9.PNG)

parte l'installazione ma mi butta fuori con l'errore che allego.

Scusa le mille domande... ma vorrei riuscire a concludere il tutto.

Grazie mille
![Cattura3](https://user-images.githubusercontent.com/65716964/98847421-83abf380-2450-11eb-84fb-c6ac78300caa.PNG)

![Cattura](https://user-images.githubusercontent.com/65716964/98843711-9f60cb00-244b-11eb-81e1-a8597b67ca66.PNG)

**Comment by bigmoby** [comment]
Ipotizziamo che il token DuckDNS sia "1234567890abcdefg" allora la riga da inserire nello shell script duck.sh sarà:

`echo url="https://www.duckdns.org/update?domains=lamiacasadicampagnia&token=1234567890abcdefg&ip=" | curl -k -o ./duck.log -K -`

ovvero devi rimuovere le parentesi quadre...dai un occhio alla documentazione DuckDNS ;-)

Per l'errore sull'installazione di PiVPN magari ti consiglierei di rimuovere iptables-persistent e lasciare che il processo di installazione di PiVPN faccia in autonomia con la versione che "gli piace".

**Comment by matthewfade** [comment]
Ho fatto come mi hai scritto... tutto ok per duck.sh

mentre per il PiVPN ancora nulla... ho cancellato come vedi iptables-persistent ma si ripete l'errore.
![Cattura](https://user-images.githubusercontent.com/65716964/98865457-b3b4c000-246b-11eb-8639-67e94d9463b7.PNG)

Non so più cosa inventarmi...
Grazie se puoi aiutarmi

**Comment by matthewfade** [comment]
ho risolto!

il mio ultimo problema è questo...
![Cattura](https://user-images.githubusercontent.com/65716964/98873863-693a4000-2479-11eb-8862-bc20d1ffd849.PNG)

Questo è l'errore all'ultimo passaggio che mi restituisce la VM dove è installato HomeAssistant

**Comment by matthewfade** [comment]
Grazie per una soluzione

**Comment by TheBigFarter** [comment]
> Ho fatto come mi hai scritto... tutto ok per duck.sh
> 
> mentre per il PiVPN ancora nulla... ho cancellato come vedi iptables-persistent ma si ripete l'errore.
> ![Cattura](https://user-images.githubusercontent.com/65716964/98865457-b3b4c000-246b-11eb-8639-67e94d9463b7.PNG)
> 
> Non so più cosa inventarmi...
> Grazie se puoi aiutarmi

Mi introduco nella discussione. Come avresti risolto? anch'io sono impantanato all'installazione di piVPN che si interrompe, con la tua medesima schermata.
Ho provveduto a disinstallare completamente `iptables-persistent` attraverso il comando `purge` ma non ho avuto modo di uscirne.

**Comment by bigmoby** [comment]
> ho risolto!
> 
> il mio ultimo problema è questo...
> ![Cattura](https://user-images.githubusercontent.com/65716964/98873863-693a4000-2479-11eb-8862-bc20d1ffd849.PNG)
> 
> Questo è l'errore all'ultimo passaggio che mi restituisce la VM dove è installato HomeAssistant

Ciao, mi servirebbero più dati per poterti essere d'aiuto. Potresti postare ad esempio il log che sta stampando il servizio.

**Comment by matthewfade** [comment]
Eccolo
![Uploading Cattura.PNG…]()

**Comment by matthewfade** [comment]
![Cattura](https://user-images.githubusercontent.com/65716964/98914717-43d52280-24c9-11eb-866c-128964da765e.PNG)

**Comment by bigmoby** [comment]
Da un velocissimo giro su internet: https://alltime.pp.ua/blog/how-to-install-wireguard-on-xubuntu-18-04/

**Comment by bigmoby** [comment]
Vi prego di prestare attenzione ai log forniti dal sistema e spendere due minuti nella risoluzione del problema. 
Tutte queste segnalazioni non sono issue.
