### ISSUE TITLE
Reindirizzamento non funziona

### ISSUE THREAD

**Issue by manny199** [bigmoby/homeassistant_nat_network#7]
Ciao, ho seguito la tua ottima guida ma, nonostante nel mio subdomain di duckdns trovi l'ip della configurazione generata su Google Cloud Platform, se tento di accedere non funziona con errore "Impossibile raggiungere ...."
Premetto che si tratta di Home Assistant Core e che dunque non ho fatto uso di alcun addon.
La procedura, come da tue indicazioni, è stata eseguita senza aver ricevuto alcun errore e anche l'aggiornamento del client duckdns da esito OK.
Nel mio router 4G (saponetta) non ho effettuato alcun port forwarding in quanto il traffico dovrebbe essere entrante nella porta 80.
Nel mio raspberry ho già un altro duckdns configurato per l'accesso normale (spero non vada in conflitto).
Ho poi provato con vari port mapping, reindirizzando sul router la porta esterna 80 alla 8123 interna facendo puntare all'indirizzo IP del raspberry ma nulla.
Hai qualche suggerimento?

**Comment by bigmoby** [comment]
Ciao... Allora, partiamo dalla fine, un servizio duckdns già operante sul tuo Raspberry non può causare un malfunzionamento simile per due ragioni: 1) immagino che sia configurato su un diverso su dominio duckdns rispetto a quello usato da GCP; 2) essendo il Raspberry in una rete natted userà un ip, con cui non può farci nulla, e sicuramente diverso da quello di GCP. Domanda: perché lo tieni operativo e non lo rimuovi?
Possiamo al problema che poni: dai log di Wireguard (o su pivpn) su GCP ti sei accertato che il client wireguard si sia connesso? Hai provato a fare un ping da GCP verso 10.6.0.2 (o ip che hai scelto per il client)?

**Comment by bigmoby** [comment]
In assenza di feedback chiudo l'issue.

**Comment by manny199** [comment]
@bigmoby 
Scusa, purtroppo il fine settimana non ho avuto accesso a github.
Grazie alla tua ottima guida sono finalmente riuscito ad effettuare il tunnel e dunque la connessione da remoto su homeassistant con SIM 4G.
Ho però bisogno di chiarire alcuni punti:

1) Certificato SSL, ho bisogno di installare il certificato in piattaforma Google, in quanto all'accesso ho sempre un messaggio di sito inaffidabile.

2) In merito al dirottamento su porta 80 verso il mio router, poiché vorrei cambiare la porta da 80 in XXXXXX, posso farlo modificando la seguente riga nel file rinetd.conf? Funziona lo stesso?
bindadress    bindport  connectaddress  connectport
0.0.0.0         80        10.6.0.2        8123

3) Purtroppo il mio raspberry non consentiva l'installazione del Client WIREGUARD poiché inesistente. Ho dovuto pertanto installare l'intero pacchetto PiVPN che comprende anche il server. Solo così sono riuscito ad installare wireguard client lanciando il comando "sudo apt install wireguard" ma ottenendo un blocco che non mi consentiva l'accesso. Ho dovuto dunque disinstallare PiVPN lasciando solo wireguard e tutto ha funzionato. C'è una soluzione alternativa per installare wireguard client direttamente?

Grazie mille

**Comment by bigmoby** [comment]
Ciao @manny199 , nessun problema 👍
Ok, quindi mi pare di aver compreso che la connessione tra broker vpn e client adesso ti funzioni pertanto, per chiarire, se punti al tuo dominio, per esempio `http://testcasa.duckdns.org`, lo raggiungi con successo. Bene 
Per installare un certificato SSL e rendere la connessione sicura leggi la seconda parte della guida: [https://github.com/bigmoby/homeassistant_nat_network/blob/main/README_IT_part_2.md](url)
Seguendola passo passo avrai la configurazione che cerchi! 👍 
Rispondo direttamente alla domanda 3 poiché la domanda 2 diverrebbe superata una volta che concluderai la seconda parte della guida. 
Risposta 3: facciamo un pò di chiarezza, l'applicazione Wireguard è una sola ma lo si può configurare o come broker o come client! Cambia soltanto il file di configurazione. Se l'hai installato con PiVPN e non direttamente come package Wireguard va benissimo ugualmente, è tutto ok! L'importante è la diversa configurazione. Se hai seguito la guida potrai notare che la semantica dei due file di configurazione, broker lato GCP e client sul Raspberry, è differente.
Ciao,
Fabio

**Comment by manny199** [comment]
Ciao Fabio, grazie per le dritte.
ti confermo che se punto al mio indirizzo raggiungo il raspberry con home assistant core con successo.
Proseguiro adesso con l'installazione del certificato SSL.
In merito a wireguard installato tramite PiVPN, dal momento che non accettava "sudo apt install wireguard" in quanto inesistente, ho dovuto procedere ad un unistall dello stesso PiVPN in quanto mi bloccava tutto e non avevo più accesso. Proprio per questo chiedevo se c'era altra strada.
Grazie ancora per la disponibilità

**Comment by bigmoby** [comment]
Ok, bene.
Per la questione dell'installazione wireguard avresti potuto anche installarlo dai sorgenti ma alla fine l'importante è che sia riuscito! 👍 Mi suona strano che non abbia trovato già i binari compilati per la tua piattaforma. Una curiosità: che distribuzione linux hai sul raspberry?
Ciao,
Fabio

**Comment by manny199** [comment]
Ciao, ho Raspbian.
Poiché sto procedendo con una nuova installazione pulita, mi dai i riferimenti di sorgenti per l'installazione del solo wireguard?
Grazie

**Comment by bigmoby** [comment]
Non so chiaramente il livello di conoscenze che hai, ad ogni modo sono qui i sorgenti: https://www.wireguard.com/compilation/
Inoltre tieni conto di questa issue aperta: https://github.com/adrianmihalko/raspberrypiwireguard/issues/13
In bocca al lupo
👍

**Comment by manny199** [comment]
@bigmoby Ciao, ho necessità di accedere al Raspberry tramite un ulteriore dominio duckdns (aggiuntivo a quello creato per GCP).
Il Raspberry è connesso al router 4G e alla rete interna cablata, per intenderci tramite RJ45.
Vorrei dunque accedere ad HA core tramite rete 4G, utilizzando un dominio duckdns, per esempio pippo4g.duckdns.org, e tramite rete cablata avvalendomi di un altro dominio per esempio pippofissa.duckdns.org. Ovviamente il Raspberry ha nel file configuration.yaml già installato il servizio per **pippofissa.duckdns.org**.
Purtroppo non riesco perchè probabilmente le regole della VPN non me lo consentono, infatti guardando gli aggiornamenti IP su duckdns, vedo che l'IP è quello della GCP.
In sostanza vorrei accedere alla tramite rete 4G con VPN e direttamente al Raspberry senza VPN.
Questo è necessario perchè se dovesse cadere il router 4G avrei sempre accesso tramite la rete cablata.
Grazie mille per la disponibilità.

**Comment by bigmoby** [comment]
Ciao, la tua richiesta esula dal contenuto della guida e chiaramente non è una issue alla guida tuttavia ...ti consiglio di configurare le due interfacce di rete (wifi e ethernet) su due indirizzi di subnet differenti. Oltre a ciò dovrai avere due istanze di wireguard client e altre due per il broker (quindi metti in conto di avere una doppia interfaccia di rete su GCP). Sui client dovrai inoltre configurare due regole di instradamento differenti su iptables, una per interfaccia di rete.
In bocca al lupo 👍

**Comment by manny199** [comment]
Grazie di tutto!!!
Anche accesso SSL su GCP ha funzionato immediatamente alla grande.
