### ISSUE TITLE
Cloud computing VM 

### ISSUE THREAD

**Issue by domoZAM** [bigmoby/homeassistant_nat_network#9]
Hi, i'm a newbie and i'm trying to follow your guide about access through double nat.
I found two problem with the preparation of VM:
I choose the options that you suggest (VM size, debian buster as OS and so on..)

when i try this command "sudo curl linux-headers-$(uname -r)", i receive this error:
curl: (6) Could not resolve host: linux-headers-5.4.89+

And when i issue this one "curl -L https://install.pivpn.io | bash", i receive this errors:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    746      0 --:--:-- --:--:-- --:--:--   743
100 83358  100 83358    0     0   199k      0 --:--:-- --:--:-- --:--:--  199k
:::
::: sudo will be used for the install.
main: line 288: /tmp/setupVars.conf: Permission denied
main: line 289: /tmp/setupVars.conf: Permission denied
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
...

Where I mistake in your opinion?

Thanks in advance for your attention.

**Comment by bigmoby** [comment]
Hi @domoZAM ,

> when i try this command "sudo curl linux-headers-$(uname -r)", i receive this error:
> curl: (6) Could not resolve host: linux-headers-5.4.89+
> 
> And when i issue this one "curl -L https://install.pivpn.io | bash", i receive this errors:
>

I don't understand why you wanna try a curl for linux-header? I think you have to invoke instead 

`sudo apt install rinetd curl linux-headers-$(uname -r)`

Then retry to follow the guide ;-)

**Comment by domoZAM** [comment]
:-)
i tried before  to simplify  my explanation but really, the first time i issue exactly the command in the guide, as now:

pinco@cloudshell:~ (axial-matter-xyz)$ sudo apt install rinetd curl linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-headers-5.4.89
E: Couldn't find any package by glob 'linux-headers-5.4.89'
E: Couldn't find any package by regex 'linux-headers-5.4.89'
pinco@cloudshell:~ (axial-matter-xyz) 

but the result is the same..

**Comment by domoZAM** [comment]
This my VM on GCP: 
homemanager
Accesso remoto
 Abilita connessione a porte seriali 
Log
Cloud Logging

Porta seriale 1 (console)
Tipo di macchina
e2-micro (2 vCPU, 1 GB di memoria)
Prenotazione
Scelta automatica
Piattaforma CPU
Unknown CPU Platform
Zona
europe-west6-a
Etichette
Nessuna
Interfacce di rete
Nome	Rete	Subnet	IP interno principale	Intervalli IP alias	IP esterno	Livello di rete 	Inoltro IP	Dettagli rete
nic0	default	default	10.172.x.y	—	
Temporaneo
Premium	
Non attivo
Record PTR DNS pubblico
Nessuno
Firewall


Consenti traffico HTTP

Consenti traffico HTTPS
Tag di rete
http-server, https-server

Servizio VM riservata 
Disattivata

Disco di avvio
Nome	Immagine	Dimensioni (GB)	Nome dispositivo	Tipo	Crittografia	Modalità	Quando si elimina un'istanza
hamanager
debian-10-buster-v20210122	10	homemanager	
Disco permanente standard
Gestita da Google
Avvio, lettura/scrittura
Elimina disco
Dischi aggiuntivi
Nessuno
Dischi locali
Nessuno
Dimensione dello stato conservato
0 GB

Shielded VM 
Attiva tutte le impostazioni per la configurazione più sicura.


Attiva Secure Boot 

Attiva vTPM 

Attiva il monitoraggio dell'integrità 
Criteri di disponibilità
Prerilasciabilità	
Non attiva (consigliata)
Host in manutenzione	
Migra istanza VM (consigliato)
Riavvio automatico	
Attivo (consigliato)
Metadati personalizzati
Nessuno
Chiavi SSH

Chiavi SSH di blocco a livello di progetto
Nessuna
Account di servizio
xyz-compute@developer.gserviceaccount.com
Ambiti di accesso API di Cloud
Consenti l'accesso predefinito
 Dettagli
REST equivalente

**Comment by bigmoby** [comment]
> :-)
> i tried before to simplify my explanation but really, the first time i issue exactly the command in the guide, as now:
> 
> pinco@cloudshell:~ (axial-matter-xyz)$ sudo apt install rinetd curl linux-headers-$(uname -r)
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package linux-headers-5.4.89
> E: Couldn't find any package by glob 'linux-headers-5.4.89'
> E: Couldn't find any package by regex 'linux-headers-5.4.89'
> pinco@cloudshell:~ (axial-matter-xyz)
> 
> but the result is the same..

Ok...unfortunately for your current kernel version there are no headers packages...this can happen!
So I suggest you to use a different kernel version and then install it image and headers packages.
In other words:
1) find the latest kernel-headers for your platform (x86-64 ...I suppose)

`apt search linux-headers`

2) install the chosen version

`sudo apt install linux-image[VERSION]`
`sudo apt install linux-headers[VERSION]`

3) update grub and reboot
